import React, { createContext, useContext, useState, ReactNode } from "react";

type Language = "en" | "hi";

const translations = {
  en: {
    home: "Home",
    startScreening: "Start Screening",
    sevenDayTrend: "7-Day Trend",
    about: "About",
    projectTitle: "Project Shishu",
    heroSubtitle: "Early-risk awareness tool for identifying possible miscarriage warning signs using symptoms and health indicators.",
    heroDescription: "Every pregnancy matters. Project Shishu empowers expecting mothers and healthcare providers with early awareness of potential risks, enabling timely medical intervention.",
    startScreeningBtn: "Start Screening",
    learnMore: "Learn More",
    patientInfo: "Patient Information",
    patientInfoDesc: "Please provide the following details for an accurate assessment.",
    name: "Name",
    age: "Age",
    weeksPregnancy: "Weeks of Pregnancy",
    bloodPressure: "Blood Pressure (optional)",
    bodyTemp: "Body Temperature (optional)",
    next: "Next",
    back: "Back",
    symptomsTitle: "Symptoms Selection",
    symptomsDesc: "Select any symptoms you are currently experiencing.",
    viewResults: "View Results",
    riskResult: "Risk Assessment Result",
    riskPercentage: "Risk Percentage",
    riskCategory: "Risk Category",
    medicalAdvice: "Medical Advice",
    viewTrend: "View 7-Day Risk Trend",
    startOver: "Start Over",
    trendTitle: "7-Day Risk Awareness Trend",
    trendDesc: "Projected risk awareness trend over the next 7 days based on your current risk percentage.",
    trendAwarenessDisclaimer: "This chart is an awareness-based projection using the current risk percentage and is not a medical diagnosis.",
    aboutTitle: "About Project Shishu",
    aboutWhyMattersTitle: "Why Miscarriage Awareness Matters",
    aboutWhyMattersDesc: "Miscarriage is far more common than most people realize — an estimated 15 to 25 percent of known pregnancies end in miscarriage. Despite this, it remains a topic surrounded by silence and stigma. By raising awareness, we can help families recognize early warning signs, seek timely medical support, and feel less alone during a difficult experience.",
    aboutWarning: "Common Warning Signs",
    aboutWarningNote: "These symptoms do not always indicate a miscarriage, but they should never be ignored. If you experience any of these, consult a healthcare professional.",
    aboutWhatToDoTitle: "What To Do If Warning Signs Appear",
    aboutStayCalmTitle: "Stay Calm",
    aboutStayCalmDesc: "Anxiety can worsen symptoms. Take deep breaths and try to stay composed while seeking help.",
    aboutSeekAdviceTitle: "Seek Medical Advice",
    aboutSeekAdviceDesc: "Call your doctor or healthcare provider immediately to describe your symptoms and get guidance.",
    aboutVisitDoctorTitle: "Visit a Professional",
    aboutVisitDoctorDesc: "Go to the nearest clinic or hospital for a proper examination and medical assessment.",
    aboutDidYouKnow: "Did You Know?",
    aboutFact1: "Around 15–25% of known pregnancies end in miscarriage, and the actual number may be higher since many occur before a pregnancy is recognized.",
    aboutFact2: "Most miscarriages occur during the first trimester (first 12 weeks). The risk decreases significantly after week 13.",
    aboutFact3: "Early medical attention and proper prenatal care can significantly reduce complications and improve outcomes for both mother and baby.",
    aboutDisclaimerTitle: "Important Disclaimer",
    aboutDisclaimerDesc: "This tool provides risk awareness only and does not diagnose medical conditions. Predictions are based on general indicators and may not always be accurate. Always consult a qualified healthcare provider for medical advice, diagnosis, or treatment.",
    disclaimer: "Disclaimer: This tool is for awareness purposes only and does not replace professional medical advice. Always consult a healthcare provider.",
    low: "Low",
    moderate: "Moderate",
    high: "High",
    critical: "Critical",
    lowAdvice: "Your risk appears low. Continue regular prenatal checkups and maintain a healthy lifestyle.",
    moderateAdvice: "Some risk factors detected. Please schedule a visit with your healthcare provider soon for a detailed evaluation.",
    highAdvice: "Multiple risk factors detected. Please seek medical attention promptly. Contact your healthcare provider today.",
    criticalAdvice: "Urgent: Several critical warning signs detected. Please go to the nearest hospital or emergency room immediately.",
    day: "Day",
    riskLevel: "Risk Level (%)",
    vaginalBleeding: "Vaginal Bleeding",
    vaginalBleedingDesc: "Any spotting or bleeding from the vagina",
    severeAbdominalPain: "Severe Abdominal Pain",
    severeAbdominalPainDesc: "Intense pain in the lower abdomen",
    severeCramps: "Severe Cramps",
    severeCrampsDesc: "Strong cramping in the pelvic area",
    lowerBackPain: "Lower Back Pain",
    lowerBackPainDesc: "Persistent pain in the lower back",
    fever: "Fever",
    feverDesc: "Body temperature above 100.4°F (38°C)",
    dizziness: "Dizziness",
    dizzinessDesc: "Feeling lightheaded or faint",
    weakness: "Weakness",
    weaknessDesc: "Unusual fatigue or lack of energy",
    tissueFluid: "Tissue or Fluid Passing",
    tissueFluidDesc: "Passing tissue or fluid from the vagina",
    // Numeric field labels
    systolic_bp: "Systolic BP",
    diastolic_bp: "Diastolic BP",
    blood_sugar: "Blood Sugar",
    body_temp: "Body Temperature",
    heart_rate: "Heart Rate",
    bmi: "BMI",
    // Numeric placeholders
    age_placeholder: "e.g. 28",
    systolic_bp_placeholder: "e.g. 120",
    diastolic_bp_placeholder: "e.g. 80",
    blood_sugar_placeholder: "e.g. 90",
    body_temp_placeholder: "e.g. 98.6",
    heart_rate_placeholder: "e.g. 72",
    bmi_placeholder: "e.g. 24.5",
    // Toggle field labels
    prev_complications: "Previous Complications",
    preexisting_diabetes: "Pre-existing Diabetes",
    gestational_diabetes: "Gestational Diabetes",
    mental_health: "Mental Health Issues",
    abdominal_pain: "Abdominal Pain",
    fever_symptom: "Fever",
    back_pain: "Back Pain",
    pelvic_cramps: "Pelvic Cramps",
    yes: "Yes",
    no: "No",
    symptomsToggleDesc: "Toggle any conditions or symptoms that apply.",
    analyzing: "Analyzing health indicators...",
    predictionError: "Prediction service unavailable. Please try again.",
    highRiskPercent: "High Risk Probability",
    trendSummaryLabel: "7-Day Projection",
    trendIncreasing: "Risk trend is increasing — seek medical advice",
    trendDecreasing: "Risk trend is decreasing with current indicators",
    trendStable: "Risk trend remains stable",
    trendExplanationTitle: "What does this trend mean?",
    trendSevereExplanation: "Severe symptoms such as vaginal bleeding or tissue passing have been detected. The risk level may remain elevated or increase over the coming days. Immediate medical consultation is strongly recommended.",
    trendModerateExplanation: "Moderate symptoms have been identified. With proper care and monitoring, the risk is expected to decrease gradually. Please consult your healthcare provider for guidance.",
    trendMildExplanation: "Mild symptoms were reported. The projected trend shows a steady decrease in risk over the next seven days. Continue monitoring and attend regular checkups.",
    trendNoneExplanation: "No concerning symptoms were reported. The risk level is projected to decrease quickly. Maintain a healthy routine and continue prenatal care.",
    trendConsultDoctor: "If symptoms persist or worsen at any point, please consult a healthcare professional immediately. This projection is for awareness only.",
  },
  hi: {
    home: "होम",
    startScreening: "स्क्रीनिंग शुरू करें",
    sevenDayTrend: "7-दिन का रुझान",
    about: "परियोजना के बारे में",
    projectTitle: "प्रोजेक्ट शिशु",
    heroSubtitle: "लक्षणों और स्वास्थ्य संकेतकों का उपयोग करके संभावित गर्भपात चेतावनी संकेतों की पहचान के लिए प्रारंभिक जोखिम जागरूकता उपकरण।",
    heroDescription: "हर गर्भावस्था मायने रखती है। प्रोजेक्ट शिशु गर्भवती माताओं और स्वास्थ्य सेवा प्रदाताओं को संभावित जोखिमों की शुरुआती जागरूकता प्रदान करता है।",
    startScreeningBtn: "स्क्रीनिंग शुरू करें",
    learnMore: "और जानें",
    patientInfo: "रोगी की जानकारी",
    patientInfoDesc: "सटीक मूल्यांकन के लिए कृपया निम्नलिखित विवरण प्रदान करें।",
    name: "नाम",
    age: "आयु",
    weeksPregnancy: "गर्भावस्था के सप्ताह",
    bloodPressure: "रक्तचाप (वैकल्पिक)",
    bodyTemp: "शरीर का तापमान (वैकल्पिक)",
    next: "अगला",
    back: "पीछे",
    symptomsTitle: "लक्षण चयन",
    symptomsDesc: "वर्तमान में आप जो भी लक्षण अनुभव कर रहे हैं उन्हें चुनें।",
    viewResults: "परिणाम देखें",
    riskResult: "जोखिम मूल्यांकन परिणाम",
    riskPercentage: "जोखिम प्रतिशत",
    riskCategory: "जोखिम श्रेणी",
    medicalAdvice: "चिकित्सा सलाह",
    viewTrend: "7-दिन का जोखिम रुझान देखें",
    startOver: "फिर से शुरू करें",
    trendTitle: "7-दिन का जोखिम जागरूकता रुझान",
    trendDesc: "आपके वर्तमान जोखिम प्रतिशत के आधार पर अगले 7 दिनों का अनुमानित जागरूकता रुझान।",
    trendAwarenessDisclaimer: "यह चार्ट वर्तमान जोखिम प्रतिशत का उपयोग करके एक जागरूकता-आधारित अनुमान है और यह चिकित्सा निदान नहीं है।",
    aboutTitle: "प्रोजेक्ट शिशु के बारे में",
    aboutWhyMattersTitle: "गर्भपात जागरूकता क्यों ज़रूरी है",
    aboutWhyMattersDesc: "गर्भपात अधिकांश लोगों की सोच से कहीं अधिक आम है — अनुमानित 15 से 25 प्रतिशत ज्ञात गर्भधारण गर्भपात में समाप्त होते हैं। जागरूकता बढ़ाकर हम परिवारों को शुरुआती चेतावनी संकेतों को पहचानने और समय पर चिकित्सा सहायता लेने में मदद कर सकते हैं।",
    aboutWarning: "सामान्य चेतावनी संकेत",
    aboutWarningNote: "ये लक्षण हमेशा गर्भपात का संकेत नहीं देते, लेकिन इन्हें नज़रअंदाज़ नहीं किया जाना चाहिए।",
    aboutWhatToDoTitle: "चेतावनी संकेत दिखने पर क्या करें",
    aboutStayCalmTitle: "शांत रहें",
    aboutStayCalmDesc: "चिंता लक्षणों को बदतर बना सकती है। गहरी सांस लें और मदद लेते समय शांत रहने का प्रयास करें।",
    aboutSeekAdviceTitle: "चिकित्सा सलाह लें",
    aboutSeekAdviceDesc: "अपने लक्षणों का वर्णन करने और मार्गदर्शन प्राप्त करने के लिए तुरंत अपने डॉक्टर को कॉल करें।",
    aboutVisitDoctorTitle: "डॉक्टर से मिलें",
    aboutVisitDoctorDesc: "उचित जांच और चिकित्सा मूल्यांकन के लिए निकटतम क्लिनिक या अस्पताल जाएं।",
    aboutDidYouKnow: "क्या आप जानते हैं?",
    aboutFact1: "लगभग 15-25% ज्ञात गर्भधारण गर्भपात में समाप्त होते हैं, और वास्तविक संख्या अधिक हो सकती है।",
    aboutFact2: "अधिकांश गर्भपात पहली तिमाही (पहले 12 सप्ताह) में होते हैं। 13वें सप्ताह के बाद जोखिम काफी कम हो जाता है।",
    aboutFact3: "शुरुआती चिकित्सा ध्यान और उचित प्रसवपूर्व देखभाल जटिलताओं को काफी कम कर सकती है।",
    aboutDisclaimerTitle: "महत्वपूर्ण अस्वीकरण",
    aboutDisclaimerDesc: "यह उपकरण केवल जोखिम जागरूकता प्रदान करता है और चिकित्सा स्थितियों का निदान नहीं करता। चिकित्सा सलाह के लिए हमेशा योग्य स्वास्थ्य सेवा प्रदाता से परामर्श करें।",
    disclaimer: "अस्वीकरण: यह उपकरण केवल जागरूकता उद्देश्यों के लिए है और पेशेवर चिकित्सा सलाह का विकल्प नहीं है।",
    low: "कम",
    moderate: "मध्यम",
    high: "उच्च",
    critical: "गंभीर",
    lowAdvice: "आपका जोखिम कम दिखता है। नियमित प्रसवपूर्व जांच जारी रखें।",
    moderateAdvice: "कुछ जोखिम कारक पाए गए। कृपया जल्द ही अपने डॉक्टर से मिलें।",
    highAdvice: "कई जोखिम कारक पाए गए। कृपया तुरंत चिकित्सा सहायता लें।",
    criticalAdvice: "तत्काल: कई गंभीर चेतावनी संकेत पाए गए। कृपया तुरंत नजदीकी अस्पताल जाएं।",
    day: "दिन",
    riskLevel: "जोखिम स्तर (%)",
    vaginalBleeding: "योनि से रक्तस्राव",
    vaginalBleedingDesc: "योनि से कोई भी स्पॉटिंग या रक्तस्राव",
    severeAbdominalPain: "गंभीर पेट दर्द",
    severeAbdominalPainDesc: "पेट के निचले हिस्से में तीव्र दर्द",
    severeCramps: "गंभीर ऐंठन",
    severeCrampsDesc: "श्रोणि क्षेत्र में तेज ऐंठन",
    lowerBackPain: "कमर दर्द",
    lowerBackPainDesc: "कमर में लगातार दर्द",
    fever: "बुखार",
    feverDesc: "शरीर का तापमान 100.4°F (38°C) से अधिक",
    dizziness: "चक्कर आना",
    dizzinessDesc: "सिर घूमना या बेहोशी महसूस होना",
    weakness: "कमज़ोरी",
    weaknessDesc: "असामान्य थकान या ऊर्जा की कमी",
    tissueFluid: "ऊतक या तरल पदार्थ का निकलना",
    tissueFluidDesc: "योनि से ऊतक या तरल पदार्थ का निकलना",
    systolic_bp: "सिस्टोलिक बीपी",
    diastolic_bp: "डायस्टोलिक बीपी",
    blood_sugar: "रक्त शर्करा",
    body_temp: "शरीर का तापमान",
    heart_rate: "हृदय गति",
    bmi: "बीएमआई",
    age_placeholder: "जैसे 28",
    systolic_bp_placeholder: "जैसे 120",
    diastolic_bp_placeholder: "जैसे 80",
    blood_sugar_placeholder: "जैसे 90",
    body_temp_placeholder: "जैसे 98.6",
    heart_rate_placeholder: "जैसे 72",
    bmi_placeholder: "जैसे 24.5",
    prev_complications: "पिछली जटिलताएं",
    preexisting_diabetes: "पहले से मधुमेह",
    gestational_diabetes: "गर्भकालीन मधुमेह",
    mental_health: "मानसिक स्वास्थ्य समस्याएं",
    abdominal_pain: "पेट दर्द",
    fever_symptom: "बुखार",
    back_pain: "पीठ दर्द",
    pelvic_cramps: "श्रोणि ऐंठन",
    yes: "हाँ",
    no: "नहीं",
    symptomsToggleDesc: "जो भी स्थितियाँ या लक्षण लागू हों उन्हें टॉगल करें।",
    analyzing: "स्वास्थ्य संकेतकों का विश्लेषण हो रहा है...",
    predictionError: "भविष्यवाणी सेवा अनुपलब्ध है। कृपया पुनः प्रयास करें।",
    highRiskPercent: "उच्च जोखिम प्रतिशत",
    trendSummaryLabel: "7-दिन का अनुमान",
    trendIncreasing: "जोखिम का रुझान बढ़ रहा है — चिकित्सा सलाह लें",
    trendDecreasing: "वर्तमान संकेतकों के साथ जोखिम का रुझान घट रहा है",
    trendStable: "जोखिम का रुझान स्थिर है",
    trendExplanationTitle: "इस रुझान का क्या मतलब है?",
    trendSevereExplanation: "योनि से रक्तस्राव या ऊतक निकलने जैसे गंभीर लक्षण पाए गए हैं। जोखिम स्तर बढ़ सकता है। तत्काल चिकित्सा परामर्श की सिफारिश की जाती है।",
    trendModerateExplanation: "मध्यम लक्षण पहचाने गए हैं। उचित देखभाल से जोखिम धीरे-धीरे कम होने की उम्मीद है। कृपया अपने डॉक्टर से परामर्श करें।",
    trendMildExplanation: "हल्के लक्षण रिपोर्ट किए गए। अगले सात दिनों में जोखिम में स्थिर कमी का अनुमान है। निगरानी जारी रखें।",
    trendNoneExplanation: "कोई चिंताजनक लक्षण नहीं पाए गए। जोखिम स्तर तेज़ी से घटने का अनुमान है। स्वस्थ दिनचर्या बनाए रखें।",
    trendConsultDoctor: "यदि लक्षण बने रहते हैं या बिगड़ते हैं, तो कृपया तुरंत किसी स्वास्थ्य पेशेवर से संपर्क करें। यह अनुमान केवल जागरूकता के लिए है।",
  },
};

interface LanguageContextType {
  lang: Language;
  setLang: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType>({
  lang: "en",
  setLang: () => {},
  t: (key: string) => key,
});

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [lang, setLang] = useState<Language>("en");
  const t = (key: string) => (translations[lang] as Record<string, string>)[key] || key;
  return (
    <LanguageContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);
